src/main/java/com/cgi/workshops/swf/dutchteamselector/model/PlayerType.java
package com.cgi.workshops.swf.dutchteamselector.model;

/**
 * PlayerType defines the type of player.
 */
public enum PlayerType {
    MIDFIELDER("label.midfielder",0), 
    ATTACKER("label.attacker",1), 
    DEFENDER("label.defender",2),
    KEEPER("label.keeper",3);
    
    private String messageKey;
    private int code;

    /**
     * Constructs a PlayerType enum for a given messageKey and code. 
     * @param messageKey resolves to a description
     * @param code for comparison between two PlayerType enumeration values
     */
    PlayerType(String messageKey, int code) {
        this.messageKey = messageKey;
        this.code = code;
    }

    /**
     * Returns the messageKey that can be resolved to a description of the playertype.
     * (e.g. 'label.midfielder' can be resolved to 'Middenvelder')
     * @return the messageKey that can be resolved to a description of the playertype.
     */
	public String getMessageKey() {
		return messageKey;
	}

	/**
	 * Returns code to be able to compare PlayerType enumeration values
	 * @return code to be able to compare PlayerType enumeration values
	 */
	public int getCode() {
		return code;
	}
}

src/main/java/com/cgi/workshops/swf/dutchteamselector/model/SearchCriteria.java
package com.cgi.workshops.swf.dutchteamselector.model;

import java.io.Serializable;

/**
 *
 * This class should implement Serializable because Spring Webflow stores the state of the model,
 * between state transitions.
 * @author kramerf
 *
 */
public class SearchCriteria implements Serializable {
	private static final long serialVersionUID = 8633619851688020608L;
	private String keyword;

	public String getKeyword() {
		return keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}
	
	
}

src/main/java/com/cgi/workshops/swf/dutchteamselector/model/SoccerPlayer.java
package com.cgi.workshops.swf.dutchteamselector.model;

import java.io.Serializable;

import org.springframework.stereotype.Component;

/**
 * Describes a player.
 * This class should implement Serializable because Spring Webflow stores the state of the model,
 * between state transitions.
 * @author kramerf
 *
 */
@Component("soccerPlayer")
public class SoccerPlayer implements Serializable {
	private static final long serialVersionUID = 1L;
	private String id;
	private String firstName;
	private String lastName;
	private int caps;
	private int minutes;
	private int goals;
	
	private PlayerType playerType;

	
	/**
	 * Returns the identifier of the soceerPlayer.
	 * @return the identifier of the soceerPlayer.
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the identifier of the soceerPlayer.
	 * @param id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Returns the firstname of the soccerPlayer.
	 * @return the firstname of the soccerPlayer.
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Sets the firstname of the soceerPlayer.
	 * @param firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Returns the lastName of the soccerPlayer.
	 * @return the lastName of the soccerPlayer.
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Sets the lastName of the soccerPlayer.
	 * @param lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * Returns the playerType of the soccerPlayer.
	 * @return the playerType of the soccerPlayer.
	 */
	public PlayerType getPlayerType() {
		return playerType;
	}

	/**
	 * Sets the playerType of the soccerPlayer.
	 * @param playerType to set
	 */
	public void setPlayerType(PlayerType playerType) {
		this.playerType = playerType;
	}
	
	/**
	 * Returns the amount of caps the soccerplayer played ('interlands' in dutch).
	 * @return the amount of caps the soccerplayer played ('interlands' in dutch).
	 */
	public int getCaps() {
		return caps;
	}

	/**
	 * Sets the amount of caps the soccerplayer played ('interlands' in dutch).
	 * @param caps to set
	 */
	public void setCaps(int caps) {
		this.caps = caps;
	}

	/**
	 * Returns the number of minutes the player was in the field. 
	 * @return the number of minutes the player was in the field
	 */
	public int getMinutes() {
		return minutes;
	}

	/**
	 * Sets the number of minutes the player was in the field
	 * @param minutes to set
	 */
	public void setMinutes(int minutes) {
		this.minutes = minutes;
	}

	/**
	 * Returns the number of goals the player made.
	 * @return the number of goals the player made.
	 */
	public int getGoals() {
		return goals;
	}

	/**
	 * Sets the number of goals the player made.
	 * @param goals to set
	 */
	public void setGoals(int goals) {
		this.goals = goals;
	}

	/**
	 * Returns the displayname (e.g. 'Daley, Blind')
	 * @return the displayname (e.g. 'Daley, Blind')
	 */
	public String getDisplayName(){
		return String.format("%s %s", firstName, lastName);
	}

	/**
	 * Overridden for debug purposes.
	 */
	@Override
	public String toString() {
		final String format = "id:%s,firstName:%s,lastName:%s,caps:%d,minutes:%d,goals:%d,playerType:%s";
		
		return String.format(format,id, firstName, lastName, caps, minutes, goals, playerType);
	}

	@Override
	public int hashCode() {
		if(id == null){
			return 0;
		}else{
			return id.hashCode();	
		}
	}

	@Override
	public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null || getClass() != other.getClass()) {
            return false;
        }

        SoccerPlayer that = (SoccerPlayer) other;
        return that.id.equals(this.id);
	}
}

src/main/java/com/cgi/workshops/swf/dutchteamselector/model/SoccerTeamSelection.java
package com.cgi.workshops.swf.dutchteamselector.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

/**
 * Holds all the selected players.
 */
@Component("soccerTeamSelection")
public class SoccerTeamSelection implements Serializable {
	private static final long serialVersionUID = -5145124885660252876L;
	
	private List<SoccerPlayer> selectedPlayers = new ArrayList<SoccerPlayer>();

	public List<SoccerPlayer> getSelectedPlayers() {
		return selectedPlayers;
	}

	public void addSoccerPlayer(SoccerPlayer soccerPlayer){
		selectedPlayers.add(soccerPlayer);
	}
}

src/main/java/com/cgi/workshops/swf/dutchteamselector/model/TeamStatistics.java
package com.cgi.workshops.swf.dutchteamselector.model;

import java.io.Serializable;

public class TeamStatistics implements Serializable {

    int experienceInCaps;
    int experienceInMinutes;
    int effectivenessInGoals;

    /**
     * Returns experience of the team (the total number of caps).
     * @return the total number of caps.
     */
    public int getExperienceInCaps() {
        return experienceInCaps;
    }

    /**
     * Sets the total number of caps.
     * @param experienceInCaps to set
     */
    public void setExperienceInCaps(int experienceInCaps) {
        this.experienceInCaps = experienceInCaps;
    }

    /**
     * Returns the experience of the team measured in minutes.
     * @return the experience of the team measured in minutes.
     */
    public int getExperienceInMinutes() {
        return experienceInMinutes;
    }

    /**
     * Sets the experience of the team measured in minutes.
     * @param experienceInMinutes to set
     */
    public void setExperienceInMinutes(int experienceInMinutes) {
        this.experienceInMinutes = experienceInMinutes;
    }

    /**
     * Returns the effectiveness of your team measured in goals
     * @return the effectiveness of your team measured in goals
     */
    public int getEffectivenessInGoals() {
        return effectivenessInGoals;
    }

    /**
     * Sets the effectiveness of your team measured in goals
     * @param effectivenessInGoals
     */
    public void setEffectivenessInGoals(int effectivenessInGoals) {
        this.effectivenessInGoals = effectivenessInGoals;
    }
}

src/main/java/com/cgi/workshops/swf/dutchteamselector/actions/FetchAllPlayersAction.java
package com.cgi.workshops.swf.dutchteamselector.actions;

import org.springframework.stereotype.Component;

@Component
public class FetchAllPlayersAction {

}

src/main/webapp/WEB-INF/flows/selectBestSoccerTeam/selectPreferredSoccerTeam.jsp
<%@page pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<HTML>
	<head>
		<title>Dutch Team Selector</title>
		<c:set var="styleUrl"><c:url value="/resources/style.css" /></c:set>
		<link type="text/css" rel="stylesheet" href="${styleUrl }">
	</head> 
	<body>
		<div id="leftcol">
			<c:url value="/resources/knvb.png" var="kvnbImageUrl" />
			<img src="${kvnbImageUrl}" /> 
		</div>
		<div id="main">
			<div id="rightcol"><h1>Selectie</h1>
				<div class="spelers">
					<c:forEach items="${ preferredSoccerTeam.selectedPlayers }" var="soccerPlayer">
						<div class="speler">${ soccerPlayer.displayName }</div>
					</c:forEach>
				</div>
				<c:url context="/" value="${flowExecutionUrl}" var="backToSearch">
					<c:param name="_eventId">showPreferred</c:param>
				</c:url>			 	
				<h2><a href="${backToSearch }">Toon Beste Team</a></h2>
			</div>
			<div id="centercol">
				<form:form method="POST" modelAttribute="searchCriteria">
					<input type="hidden" name="_flowExecutionKey" value="${flowExecutionKey}"/>
					<form:errors path="*" />
					<div class="centered">
						<label>Zoek spelers</label>
						<form:input cssClass="zoekArgument" path="keyword"></form:input>
						<input type="submit" class="button" name="_eventId_search" value="Search"/>
					</div>
				</form:form>
				<table>
				<c:forEach items="${ foundSoccerPlayers }" var="soccerPlayer">
					<tr class="player">
						<c:url value="/resources/playerBlack.png" var="playerBlackImageUrl" />
						<td class="label"><img src="${playerBlackImageUrl}" /></td>
						
						<c:url context="/" value="${flowExecutionUrl}" var="selectPlayerUrl">
							<c:param name="_eventId">select</c:param>
							<c:param name="playerId">${soccerPlayer.id}</c:param>
						</c:url>
						
						<td class="name"><a href="${selectPlayerUrl}"> ${ soccerPlayer.firstName } ${ soccerPlayer.lastName }</a></td>
					</tr>
				</c:forEach>
				</table>
			</div>
		</div>
		<br id="footerbr" />
		<div id="footer"><h6>franzzle.com Copyright</h6></div>
	</body>

</html>

src/main/webapp/WEB-INF/flows/selectBestSoccerTeam/showPreferredSoccerTeam.jsp
<%@page pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<HTML>
	<head>
		<title>Dutch Team Selector</title>
		<c:set var="styleUrl"><c:url value="/resources/style.css" /></c:set>
		<link type="text/css" rel="stylesheet" href="${styleUrl }">
	</head> 
	<body>

		<div id="leftcol">
			<c:url value="/resources/knvb.png" var="kvnbImageUrl" />
			<img src="${kvnbImageUrl}" /> 
		</div>
		<div id="main">
			<div id="rightcol">

			</div>
			<div id="centercol">
				<h1>Selectie</h1>
				<div class="spelers">
					<c:forEach items="${ preferredSoccerTeam.selectedPlayers }" var="soccerPlayer">
						<div class="speler">${ soccerPlayer.displayName }</div>
					</c:forEach>
				</div>
				
				
				<h1>Team statistieken</h1>
                <div><label>Totaal aantal interlands : </label>${teamStatistics.experienceInCaps}</div>
                <div><label>Totaal aantal minuten : </label>${teamStatistics.experienceInMinutes}</div>
                <div><label>Totaal aantal goals : </label>${teamStatistics.effectivenessInGoals}</div>
			
				<c:url context="/" value="${flowExecutionUrl}" var="backToSearch">
					<c:param name="_eventId">backToSearch</c:param>
				</c:url>			 	
				<h2><a href="${backToSearch }">Terug om te zoeken</a></h2>
			
			</div>
		</div>
		<br id="footerbr" />
		<div id="footer"><h6>franzzle.com Copyright</h6></div>
	</body>
</html>	
		

src/main/webapp/index.jsp
<jsp:forward page="selectDutchTeamHandler"></jsp:forward>